---
title: "Bayesian Models"
author: "Paige Park"
date: "2024-10-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages 
```{r}
library(BayesMortalityPlus) # updated june 4, 2024
library(tidyverse)
```

Load data
```{r}
usmdb <- read.csv("../data/usmdb/usmdb.csv", header = TRUE)
hmd <- read.csv("../data/hmd.csv", header = TRUE)
```

Prep data
```{r}
us <- usmdb |>
  filter(Age != "110+") |>
  mutate(Age = as.integer(Age)) |>
  filter(Age <= 99) |>
  mutate(log_mx = log(mx))

crty <- hmd |>
  filter(Age != "110+") |>
  mutate(Age = as.integer(Age)) |>
  filter(Age <= 99) |>
  mutate(log_mx = log(mx))
```

Split data
```{r}
training_us <- us |>
  filter(Year >= 1959 & Year <= 2005)

test_us <- us |>
  filter(Year > 2005 & Year <= 2015)

training_crty <- crty |>
  filter(Year >= 1959 & Year <= 2005)

test_crty <- crty |>
  filter(Year > 2005 & Year <= 2015)
```

Model Fitting

This analysis used the package BayesMortalityPlus & the Bayesian Lee Carter model proposed by Pedroza (2006)
```{r}

```

Predict on test data
```{r}

```

Get MSE results
```{r}

```

